name: Accessibility Check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      url:
        description: "URL to be checked (e.g.: blog/)"
        required: false

env:
  URL: ""

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false
      - name: Configure Bundler 🔧
        run: |
          rm -f Gemfile.lock
          bundle config set --local frozen false
          bundle install --jobs 4
      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 📦
        run: npm install -g @axe-core/cli
      - name: Build site 🏗️
        run: bundle exec jekyll build
      - name: Run axe 🔍
        run: npx axe http://localhost:4000 --tags wcag2a,wcag2aa
