name: Comment on PR with Prettier diff

on:
  repository_dispatch:
    types: [prettier-failed-on-pr]

jobs:
  comment:
    runs-on: ubuntu-22.04
    steps:
      - name: Download diff artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: prettier.yml
          run_id: ${{ github.event.client_payload.run_id }}
          name: HTML Diff
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('diff.html', 'utf8');
            github.rest.issues.createComment({
              issue_number: ${{ github.event.client_payload.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Prettier found some formatting issues. Please review the diff below:\n\n${diff}`
            });
